stages:
  - lint
  - test
  - build

.go-cache:
  before_script:
    - export GOPATH=/go
    - export GOPRIVATE=*.city-srv.ru
    - export GOPROXY=direct
    - go mod tidy -v

Linters:
  extends: .go-cache
  stage: lint
  image: golang:1.14
  script:
    - make lint-install
    - make lint
  tags:
    - docker

Tests:
  extends: .go-cache
  stage: test
  image: golang:1.14
  script:
    - make test
  tags:
    - docker

Coverage:
  extends: .go-cache
  stage: test
  image: golang:1.14
  script:
    - make test-coverage
  tags:
    - docker

build_docker:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - docker build -t $IMAGE:$CI_COMMIT_REF_SLUG -f Dockerfile .
    - docker push $IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker
  only:
    refs:
      - development
      - master